#ifndef ERROR_H
#define ERROR_H

typedef enum Error_Kind
{
	Error_Kind__None,
	Error_Kind__String_Multiline_Unsupported,
	Error_Kind__String_Literal_Unterminated,
	Error_Kind__Escape_Sequence_Invalid,
	Error_Kind__Character_Literal_Multiline_Unsupported,
	Error_Kind__Character_Literal_Empty,
	Error_Kind__Character_Literal_Multiple,
	Error_Kind__Character_Literal_Escape_Invalid,
	Error_Kind__Character_Literal_Unterminated,
	Error_Kind__Numeric_Literal_Invalid,
	Error_Kind__Numeric_Hex_Literal_Invalid,
	Error_Kind__Numeric_Octal_Literal_Invalid,
	Error_Kind__Numeric_Binary_Literal_Invalid,
	Error_Kind__Character_Unexpected,
	Error_Kind__Escape_Sequence_Unterminated,
	Error_Kind__Label_Directive_Invalid,

	Error_Kind__Line_Invalid,
	Error_Kind__Line_Extra_Content,
	Error_Kind__Identifier_Expected,
	Error_Kind__Comma_Expected,
	Error_Kind__Parenthesis_Left_Expected,
	Error_Kind__Parenthesis_Right_Expected,
	Error_Kind__Directive_Unknown,
	Error_Kind__Directive_Section_Argument_Missing,
	Error_Kind__Directive_Section_Argument_Invalid,
	Error_Kind__Directive_Align_Argument_Missing,
	Error_Kind__Directive_Align_Argument_Invalid,
	Error_Kind__Directive_Data_Invalid,
	Error_Kind__Directive_Data_Value_Size_Invalid,
	Error_Kind__Directive_Argument_Invalid,
	Error_Kind__Label_Duplicate,
	Error_Kind__Label_Numeric_Large,
	Error_Kind__Expression_Unexpected_Token,
	Error_Kind__Expression_Unexpected_End,
	Error_Kind__Expression_Parenthesis_Right_Expected,
	Error_Kind__Expression_Parenthesis_Left_Expected,
	Error_Kind__Expression_Identifier_Undefined,
	Error_Kind__Expression_Relocation_Syntax_Invalid,
	Error_Kind__Expression_Kind_Unknown,
	Error_Kind__Expression_Recursion_Max,
	Error_Kind__Relocation_Operator_Invalid,
	Error_Kind__Relocation_Instruction_Missing,
	Error_Kind__Relocation_Instruction_Invalid,
	Error_Kind__Relocation_Symbol_Missing,
	Error_Kind__Register_Invalid,
	Error_Kind__Immediate_Invalid,
	Error_Kind__Instruction_Unknown,
	Error_Kind__String_Literal_Expected,
	Error_Kind__Symbol_Demoted,
	Error_Kind__Symbol_Duplicate,
	Error_Kind__Symbol_Context_Invalid,
	Error_Kind__Fence_Operand_Invalid,
	Error_Kind__Option_Invalid,
	Error_Kind__Relocation_Operator_Multiple,

	Error_Kind__Expression_Evaluation_Cross,
	Error_Kind__Evaluation_Absolute_Expected,
	Error_Kind__Evaluation_Constant_Expected,
	Error_Kind__Expression_Symbol_Operand,
	Error_Kind__Expression_Value_Bounds_Outside,
	Error_Kind__Instruction_Expression_Unresolved_Symbols,
	Error_Kind__Label_Numeric_Backward_Not_Found,
	Error_Kind__Label_Numeric_Forward_Not_Found,
	Error_Kind__Label_Numeric_Section_Cross,
	Error_Kind__Section_Relocation_Invalid,
	Error_Kind__Relocation_Operand_Invalid,
	Error_Kind__Relocation_Operand_Symbol_Missing,
	Error_Kind__Relocation_Operator_Expression_Invalid,
	Error_Kind__Relocation_Operator_Expression_Unresolved_Expected,
	Error_Kind__Relocation_Operator_Unexpected,
	Error_Kind__Relocation_Operator_Expected,
	Error_Kind__Relocation_Form_Invalid,
	Error_Kind__Relocation_Expression_Invalid,
	Error_Kind__Relocation_Byte,
	Error_Kind__Symbol_Cyclic,
	Error_Kind__Operator_Between_Symbols_Invalid,
	Error_Kind__Operator_Expression_Absolute_Expected,
	Error_Kind__Immediate_Large,
	Error_Kind__Instruction_Relocation_Low_12_Expected,
	Error_Kind__Shift_Amount_Invalid,

	Error_Kind__COUNT
}
Error_Kind;

global const char *error_kind_messages[Error_Kind__COUNT] =
{
	[Error_Kind__None]                                               = "",
	[Error_Kind__String_Multiline_Unsupported]                       = "multiline strings are not supported",
	[Error_Kind__String_Literal_Unterminated]                        = "string literal unterminated",
	[Error_Kind__Escape_Sequence_Invalid]                            = "escape sequence invalid",
	[Error_Kind__Character_Literal_Multiline_Unsupported]            = "multiline character literals are not supported",
	[Error_Kind__Character_Literal_Empty]                            = "empty character literal",
	[Error_Kind__Character_Literal_Multiple]                         = "character literal contains multiple characters",
	[Error_Kind__Character_Literal_Escape_Invalid]                   = "character literal contains invalid escape",
	[Error_Kind__Character_Literal_Unterminated]                     = "character literal untermindated",
	[Error_Kind__Numeric_Literal_Invalid]                            = "numerical literal is invalid",
	[Error_Kind__Numeric_Hex_Literal_Invalid]                        = "numerical hex literal is invalid",
	[Error_Kind__Numeric_Octal_Literal_Invalid]                      = "numerical octal literal is invalid",
	[Error_Kind__Numeric_Binary_Literal_Invalid]                     = "numerical binary literal is invalid",
	[Error_Kind__Escape_Sequence_Unterminated]                       = "escape sequence unterminated",
	[Error_Kind__Label_Directive_Invalid]                            = "invalid label or directive",
	[Error_Kind__Character_Unexpected]                               = "unexpected character",

	[Error_Kind__Line_Invalid]                                       = "line can only start with a directive, label or instruction",
	[Error_Kind__Line_Extra_Content]                                 = "line ends with unexpected tokens",
	[Error_Kind__Identifier_Expected]                                = "expected identifier",
	[Error_Kind__Comma_Expected]                                     = "comma expected",
	[Error_Kind__Parenthesis_Left_Expected]                          = "left parenthesis expected",
	[Error_Kind__Parenthesis_Right_Expected]                         = "right parenthesis expected",
	[Error_Kind__Directive_Unknown]                                  = "unknown directive found",
	[Error_Kind__Directive_Section_Argument_Missing]                 = "section directive is missing the argument",
	[Error_Kind__Directive_Section_Argument_Invalid]                 = "section directive argument is invalid",
	[Error_Kind__Directive_Align_Argument_Missing]                   = "align directive is missing the argument",
	[Error_Kind__Directive_Align_Argument_Invalid]                   = "align directive argument is not a number literal",
	[Error_Kind__Directive_Data_Invalid]                             = "invalid data directive syntax",
	[Error_Kind__Directive_Data_Value_Size_Invalid]                  = "directive data expression value doesn't fit",
	[Error_Kind__Directive_Argument_Invalid]                         = "directive argument invalid",
	[Error_Kind__Label_Duplicate]                                    = "duplicate label found",
	[Error_Kind__Label_Numeric_Large]                                = "numerical label must be less than " stringify_m(label_numeric_max),
	[Error_Kind__Expression_Unexpected_Token]                        = "unexpected token in expression",
	[Error_Kind__Expression_Unexpected_End]                          = "unexpected end of tokens in expression",
	[Error_Kind__Expression_Parenthesis_Right_Expected]              = "expected ')' to close parenthesized expression",
	[Error_Kind__Expression_Parenthesis_Left_Expected]               = "expected '(' to open parenthesized expression",
	[Error_Kind__Expression_Identifier_Undefined]                    = "undefined identifier are not allowed in this expression",
	[Error_Kind__Expression_Relocation_Syntax_Invalid]               = "invalid relocation syntax, expected %<relocation>(<expression>)",
	[Error_Kind__Expression_Kind_Unknown]                            = "unknown expression kind",
	[Error_Kind__Expression_Recursion_Max]                           = "max recursion reached for expression: " stringify_m(expression_recursion_max),
	[Error_Kind__Relocation_Operator_Invalid]                        = "relocation operator invalid",
	[Error_Kind__Relocation_Instruction_Missing]                     = "relocation operator can be used only within an instruction",
	[Error_Kind__Relocation_Instruction_Invalid]                     = "relocation operator cannot be with this instruction",
	[Error_Kind__Relocation_Symbol_Missing]                          = "relocation operator used without a symbol",
	[Error_Kind__Register_Invalid]                                   = "register invalid",
	[Error_Kind__Immediate_Invalid]                                  = "immediate invalid",
	[Error_Kind__Instruction_Unknown]                                = "instruction unknown",
	[Error_Kind__String_Literal_Expected]                            = "string literal expected",
	[Error_Kind__Symbol_Demoted]                                     = "demoted symbol from global/weak to local",
	[Error_Kind__Symbol_Duplicate]                                   = "duplicated symbol",
	[Error_Kind__Symbol_Context_Invalid]                             = "invalid symbol context: must be either a data directive, a supported branch/jump instruction or inside relocation operator",
	[Error_Kind__Fence_Operand_Invalid]                              = "fence operand invalid",
	[Error_Kind__Option_Invalid]                                     = "invalid option",
	[Error_Kind__Relocation_Operator_Multiple]                       = "multiple relocation operators in the same statement is invalid",

	[Error_Kind__Expression_Kind_Unknown]                            = "expression unknown",
	[Error_Kind__Expression_Evaluation_Cross]                        = "expression involved evaluation of two symbols from different sections",
	[Error_Kind__Evaluation_Absolute_Expected]                       = "statement expects absolute expression",
	[Error_Kind__Evaluation_Constant_Expected]                       = "statement expects constant expression",
	[Error_Kind__Expression_Symbol_Operand]                          = "expression doesn't support operations with unresolved symbols",
	[Error_Kind__Expression_Value_Bounds_Outside]                    = "expression value doesn't fit instruction",
	[Error_Kind__Instruction_Expression_Unresolved_Symbols]          = "instruction expression can have at most one unresolved symbol",
	[Error_Kind__Label_Numeric_Backward_Not_Found]                   = "label numeric backward reference not found",
	[Error_Kind__Label_Numeric_Forward_Not_Found]                    = "label numeric backward reference not found",
	[Error_Kind__Label_Numeric_Section_Cross]                        = "label numeric reference crosses section",
	[Error_Kind__Relocation_Operand_Invalid]                         = "only addition and subtraction can be done for relocations",
	[Error_Kind__Relocation_Operand_Symbol_Missing]                  = "relocation has expression without symbol",
	[Error_Kind__Relocation_Operator_Expression_Invalid]             = "relocation operator has invalid subexpression",
	[Error_Kind__Relocation_Operator_Expression_Unresolved_Expected] = "relocation operator expression unresolved expected",
	[Error_Kind__Relocation_Operator_Unexpected]                     = "relocation operator unexpected",
	[Error_Kind__Relocation_Operator_Expected]                       = "relocation operator expected",
	[Error_Kind__Relocation_Symbol_Missing]                          = "relocation operator without symbol",
	[Error_Kind__Relocation_Form_Invalid]                            = "relocation can only be of the form symbol + addend",
	[Error_Kind__Relocation_Expression_Invalid]                      = "expression contains relocation operator mixed with other symbol expressions",
	[Error_Kind__Relocation_Byte]                                    = "relocation of one byte is unsupported in ELF",
	[Error_Kind__Operator_Between_Symbols_Invalid]                   = "only subtraction between symbols is supported",
	[Error_Kind__Operator_Expression_Absolute_Expected]              = "expression operator expects absolute subexpression",
	[Error_Kind__Immediate_Large]                                    = "immediate too large",
	[Error_Kind__Instruction_Relocation_Low_12_Expected]             = "instruction expects a relocation operator which takes low 12 bits if the symbol is unresolved",
	[Error_Kind__Shift_Amount_Invalid]                               = "shift amount must be in [0,64) on RISCV-64",
	[Error_Kind__Symbol_Cyclic]                                      = "cyclic symbol definition",
};

#endif // ERROR_H

