#ifndef PARSER_CORE_H
#define PARSER_CORE_H

typedef enum Parser_Error_Kind
{
	Parser_Error_Kind__None,
	Parser_Error_Kind__Line_Invalid,
	Parser_Error_Kind__Line_Extra_Content,
	Parser_Error_Kind__Identifier_Expected,
	Parser_Error_Kind__Comma_Expected,
	Parser_Error_Kind__Parenthesis_Left_Expected,
	Parser_Error_Kind__Parenthesis_Right_Expected,
	Parser_Error_Kind__Directive_Unknown,
	Parser_Error_Kind__Directive_Section_Argument_Missing,
	Parser_Error_Kind__Directive_Section_Argument_Invalid,
	Parser_Error_Kind__Directive_Align_Argument_Missing,
	Parser_Error_Kind__Directive_Align_Argument_Invalid,
	Parser_Error_Kind__Directive_Data_Invalid,
	Parser_Error_Kind__Directive_Data_Value_Size_Invalid,
	Parser_Error_Kind__Directive_Argument_Invalid,
	Parser_Error_Kind__Label_Duplicate,
	Parser_Error_Kind__Label_Numeric_Large,
	Parser_Error_Kind__Expression_Parenthesis_Left_Unclosed,
	Parser_Error_Kind__Expression_Parenthesis_Right_Unmatching,
	Parser_Error_Kind__Expression_Unexpected_Token,
	Parser_Error_Kind__Expression_Unexpected_End,
	Parser_Error_Kind__Expression_Parenthesis_Right_Expected,
	Parser_Error_Kind__Expression_Parenthesis_Left_Expected,
	Parser_Error_Kind__Expression_Identifier_Undefined,
	Parser_Error_Kind__Expression_Relocation_Syntax_Invalid,
	Parser_Error_Kind__Expression_Kind_Unknown,
	Parser_Error_Kind__Expression_Null_Denotation_Expected,
	Parser_Error_Kind__Relocation_Operator_Invalid,
	Parser_Error_Kind__Relocation_Instruction_Missing,
	Parser_Error_Kind__Relocation_Instruction_Invalid,
	Parser_Error_Kind__Relocation_Symbol_Missing,
	Parser_Error_Kind__Register_Invalid,
	Parser_Error_Kind__Immediate_Invalid,
	Parser_Error_Kind__Instruction_Unknown,
	Parser_Error_Kind__String_Literal_Expected,
	Parser_Error_Kind__Symbol_Demoted,
	Parser_Error_Kind__Symbol_Duplicate,
	Parser_Error_Kind__Symbol_Context_Invalid,
	Parser_Error_Kind__Fence_Operand_Invalid,
	Parser_Error_Kind__Option_Invalid,
	Parser_Error_Kind__Relocation_Operator_Multiple,

	Parser_Error_Kind__COUNT,
}
Parser_Error_Kind;

global const String8 Parser_Error_Kind_messages[Parser_Error_Kind__COUNT] =
{
	[Parser_Error_Kind__None]                                    = String8__literal(""),
	[Parser_Error_Kind__Line_Invalid]                            = String8__literal("line can only start with a directive), label or instruction"),
	[Parser_Error_Kind__Line_Extra_Content]                      = String8__literal("line ends with unexpected tokens"),
	[Parser_Error_Kind__Identifier_Expected]                     = String8__literal("expected identifier"),
	[Parser_Error_Kind__Comma_Expected]                          = String8__literal("comma expected"),
	[Parser_Error_Kind__Parenthesis_Left_Expected]               = String8__literal("left parenthesis expected"),
	[Parser_Error_Kind__Parenthesis_Right_Expected]              = String8__literal("right parenthesis expected"),
	[Parser_Error_Kind__Directive_Unknown]                       = String8__literal("unknown directive found"),
	[Parser_Error_Kind__Directive_Section_Argument_Missing]      = String8__literal("section directive is missing the argument"),
	[Parser_Error_Kind__Directive_Section_Argument_Invalid]      = String8__literal("section directive argument is invalid"),
	[Parser_Error_Kind__Directive_Align_Argument_Missing]        = String8__literal("align directive is missing the argument"),
	[Parser_Error_Kind__Directive_Align_Argument_Invalid]        = String8__literal("align directive argument is not a number literal"),
	[Parser_Error_Kind__Directive_Data_Invalid]                  = String8__literal("invalid data directive syntax"),
	[Parser_Error_Kind__Directive_Data_Value_Size_Invalid]       = String8__literal("directive data expression value doesn't fit"),
	[Parser_Error_Kind__Directive_Argument_Invalid]              = String8__literal("directive argument invalid"),
	[Parser_Error_Kind__Label_Duplicate]                         = String8__literal("duplicate label found"),
	[Parser_Error_Kind__Label_Numeric_Large]                     = String8__literal("numerical label must be less than " stringify_m(label_numeric_max)),
	[Parser_Error_Kind__Expression_Parenthesis_Left_Unclosed]    = String8__literal("unclosed '('"),
	[Parser_Error_Kind__Expression_Parenthesis_Right_Unmatching] = String8__literal("unexpected ')' to close non-matching '('"),
	[Parser_Error_Kind__Expression_Unexpected_Token]             = String8__literal("unexpected token in expression"),
	[Parser_Error_Kind__Expression_Unexpected_End]               = String8__literal("unexpected end of tokens in expression"),
	[Parser_Error_Kind__Expression_Parenthesis_Right_Expected]   = String8__literal("expected ')' to close parenthesized expression"),
	[Parser_Error_Kind__Expression_Parenthesis_Left_Expected]    = String8__literal("expected '(' to open parenthesized expression"),
	[Parser_Error_Kind__Expression_Identifier_Undefined]         = String8__literal("undefined identifier are not allowed in this expression"),
	[Parser_Error_Kind__Expression_Relocation_Syntax_Invalid]    = String8__literal("invalid relocation syntax), expected %<relocation>(<expression>)"),
	[Parser_Error_Kind__Expression_Kind_Unknown]                 = String8__literal("unknown expression kind"),
	[Parser_Error_Kind__Expression_Null_Denotation_Expected]     = String8__literal("expected number, symbol or unary operator"),
	[Parser_Error_Kind__Relocation_Operator_Invalid]             = String8__literal("relocation operator invalid"),
	[Parser_Error_Kind__Relocation_Instruction_Missing]          = String8__literal("relocation operator can be used only within an instruction"),
	[Parser_Error_Kind__Relocation_Instruction_Invalid]          = String8__literal("relocation operator cannot be with this instruction"),
	[Parser_Error_Kind__Relocation_Symbol_Missing]               = String8__literal("relocation operator used without a symbol"),
	[Parser_Error_Kind__Register_Invalid]                        = String8__literal("register invalid"),
	[Parser_Error_Kind__Immediate_Invalid]                       = String8__literal("immediate invalid"),
	[Parser_Error_Kind__Instruction_Unknown]                     = String8__literal("instruction unknown"),
	[Parser_Error_Kind__String_Literal_Expected]                 = String8__literal("string literal expected"),
	[Parser_Error_Kind__Symbol_Demoted]                          = String8__literal("demoted symbol"),
	[Parser_Error_Kind__Symbol_Duplicate]                        = String8__literal("duplicated symbol"),
	[Parser_Error_Kind__Symbol_Context_Invalid]                  = String8__literal("invalid symbol context: must be either a data directive), a supported branch/jump instruction or inside relocation operator"),
	[Parser_Error_Kind__Fence_Operand_Invalid]                   = String8__literal("fence operand invalid"),
	[Parser_Error_Kind__Option_Invalid]                          = String8__literal("invalid option"),
	[Parser_Error_Kind__Relocation_Operator_Multiple]            = String8__literal("multiple relocation operators in the same statement is invalid"),
};

#endif // PARSER_CORE_H
